<a href="https://colab.research.google.com/github/d3nnyyy/AI-Exploration/blob/master/DeepLearning/PyTorchIn26Hrs/00_pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on `torch.Tensor` and for `torch.cuda`.

2. Create a random tensor with shape (7, 7).

In [2]:
import torch
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.5475, 0.3930, 0.2533, 0.2230, 0.9504, 0.7542, 0.8711],
        [0.3997, 0.5599, 0.1151, 0.1373, 0.3219, 0.9051, 0.2309],
        [0.6001, 0.9152, 0.6415, 0.4174, 0.7054, 0.6363, 0.4509],
        [0.9571, 0.3651, 0.2503, 0.4532, 0.4929, 0.1551, 0.7517],
        [0.8258, 0.4521, 0.3123, 0.6483, 0.7338, 0.7088, 0.8318],
        [0.4120, 0.9829, 0.3430, 0.6473, 0.4357, 0.0755, 0.5263],
        [0.5052, 0.5369, 0.4432, 0.7191, 0.8846, 0.7045, 0.4142]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [3]:
random_tensor @ torch.rand(1,7).T

tensor([[1.8356],
        [1.1713],
        [1.5797],
        [1.2663],
        [1.9389],
        [1.1937],
        [1.7521]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.


In [4]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(1,7)
random_tensor_A @ random_tensor_B.T

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.


In [10]:
GPU_RANDOM_SEED = 1234

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).


In [13]:
torch.cuda.manual_seed(GPU_RANDOM_SEED)
gpu_rand_tensor_1 = torch.rand(2,3, device="cuda")
torch.cuda.manual_seed(GPU_RANDOM_SEED)
gpu_rand_tensor_2 = torch.rand(2,3, device="cuda")

gpu_rand_tensor_1, gpu_rand_tensor_2

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [14]:
matrix_mul = torch.mm(gpu_rand_tensor_1,gpu_rand_tensor_2.T)
matrix_mul

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.


In [15]:
torch.min(matrix_mul)

tensor(0.8358, device='cuda:0')

9. Find the maximum and minimum index values of the output of 7.


In [16]:
max_index = torch.argmax(matrix_mul)
min_index = torch.argmin(matrix_mul)
max_index, min_index

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [19]:
torch.manual_seed(7)
x = torch.rand(1,1,1,10)
x_without_1s = x.squeeze()
x.shape, x_without_1s.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))