<a href="https://colab.research.google.com/github/d3nnyyy/AI-Exploration/blob/master/DeepLearning/PyTorchIn26Hrs/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


# Tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

## Random tensors

In [10]:
# create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6600, 0.2820, 0.9747, 0.0989],
        [0.9748, 0.2569, 0.9715, 0.2578],
        [0.9756, 0.6804, 0.0051, 0.6843]])

In [11]:
# create a random tensor with similar page to an image tensor
random_img_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (R,G,B)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [12]:
# tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Range of tensors

In [13]:
# use torch.range()
zero_to_nine = torch.arange(0,10, step=1)
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [15]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [16]:
float_32_tensor.dtype


torch.float32

In [17]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [18]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [19]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Manipulating Tensors (operations)



*   Addition
*   Substraction
*   Multiplication
*   Division
*   Matrix multiplication


In [25]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [26]:
tensor*10

tensor([10, 20, 30])

In [27]:
tensor - 10

tensor([-9, -8, -7])

In [34]:
tensor / max(tensor)

tensor([0.3333, 0.6667, 1.0000])

In [35]:
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in DL : shape errors

In [50]:
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10], [8,11], [9,12]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min,max,mean,sum, etc(tensor aggregation)

In [51]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
x_float = x.type(torch.float32)
x_float.mean()

tensor(45.)

In [56]:
x.sum()

tensor(450)

In [57]:
x.argmin()

tensor(0)

## Reshaping, stacking, squeezing, unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* Returns a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each others (vstack) or side by side(hstack)
* Squeezing 0 removes all `1` dimensions
* Unsqueezing - adds a `1` dimension to a target tensor
* Permuting - returns a view of the input with dimensions permuted in a certain way

In [69]:
import torch
x = torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [70]:
# add an extra dimension
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [73]:
# change the view
z = x.view(3,4)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [75]:
# changing z changes x(because view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 5., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]))

In [77]:
# stack tesnors on top of each others
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 5.,  5.,  5.,  5.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [86]:
# torch.squeeze() - removes all single dimensions from a target tensor

x_reshaped = x_reshaped.reshape(1,12)

x_reshaped, x_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [89]:
x_squeezed = x_reshaped.squeeze()
x_squeezed,x_squeezed.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]),
 torch.Size([12]))

In [91]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
x_unsqueezed = x.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape


(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [96]:
# torch.permute() - returns a view of the input with dimensions permuted in a certain way
x_originial = torch.rand(size=(224,224,3)) # height, width, channels
x_permuted = x_originial.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

## Indexing (selecting data from tensors)

In [97]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [98]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
x[0][1]

tensor(6)

In [103]:
x[0][1][1]

tensor(5)

In [107]:
x[0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [111]:
x[0].T[2][:]

tensor([3, 6, 9])

In [113]:
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors & NumPy

In [115]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [120]:
array = array+1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([3., 3., 3., 3., 3., 3., 3.]))

In [121]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [123]:
tensor = tensor+1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([3., 3., 3., 3., 3., 3., 3.]))

## Reproducibility (random out of random)


In [138]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5259, 0.1195, 0.7799, 0.2899],
        [0.0373, 0.4352, 0.3768, 0.4487],
        [0.9215, 0.7646, 0.8603, 0.6656]])
tensor([[0.2176, 0.2174, 0.4887, 0.0894],
        [0.3778, 0.0892, 0.9172, 0.4501],
        [0.7719, 0.4593, 0.6643, 0.3826]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [143]:
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs

In [1]:
!nvidia-smi

Sun Dec 24 09:00:49 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [7]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [10]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [12]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & Extra-curriculum